### ISSUE TITLE
ElasticSearch does not return expected results

### ISSUE THREAD

**Issue by dodobas** [nyaruka/rp-indexer#15]
- an issue was reported by a user: https://app.intercom.io/a/apps/l6e7tr01/inbox/inbox/conversation/20726038791
- the reason why this is happening is ES index definition parameter for text field values: `ignore_above: 64` - https://github.com/nyaruka/rp-indexer/blob/f57fbc32cb360749da185fa2bc8e9ec155b48398/indexer.go#L495
  - this parameter prevents indexing of contact field values that are longer than 64 characters
  - https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html
- at the moment we define the max size of a text field value in the project settings: `VALUE_FIELD_SIZE = 640`
  - https://github.com/nyaruka/rapidpro/blob/41277f92c0e6f6914324ef5826ee63b30d4067c2/temba/settings_common.py#L1067

The options are to redefine the index for text fields and reindex all contacts:
  - set `"ignore_above": 640`
  - remove the param

**Comment by nicpottier** [comment]
So root problem here is that we are not tokenizing text fields in any way, just storing them as single tokens, which makes exact searching work well but really bloats our IFI if we start storing arbitrary length tokens.

We have a few different ways we can go:
 1. increase `ignore_above` to 640. this will add every field value greater than 64 to our IFI which wasn't previously there. May work short term (though also may not), but definitely going to be troublesome long term.
 2. truncate our field at 64 characters, that would prevent an empty or non-empty search from matching. Should bloat us less than 1) above but will also have an effect on our size. Difference between these two may not be that big in practice depending on the content of the first 64 and their uniqueness. (though his specific example is a case that would likely lead to some repeat keys)
 3. start tokenizing text fields, use `match_phrase` queries (so tokens next to each other) then do additional filtering on the backside. This likely leads to a *decrease* in total IFI size (truth will be in the pudding), but requires more work in interpreting results from ES. IE, we need to then filter based on the results. It would also enable users doing substring searches on values which would be neat.

As a short term fix, seems like 1) or 2) are both probably fine on TextIt/Rapid with a slight nod towards 2) from an index bloat point of view. Either of those probably blows up if we try it on say resist where they stuff entire letters in fields and have a max field size in the thousands of chars.

I think either way we want 3) sooner rather than later though.

@ericnewcomer @rowanseymour thoughts?

**Comment by nicpottier** [comment]
Went for path of least resistance since this is a temporary solution and did 1)

Need to tackle 3) as a real solution though.

**Comment by nicpottier** [comment]
This was fixed, closing.
